language: python
install:
   pip3 install --upgrade pip
script:
   - bash build.sh
before_deploy:
   - # Set up git user name and tag this commit
   - git config --local user.name "Viu-Long Kong"
   - git config --local user.email "viulong.kong@fr.ibm.com"
   - if [ "x$TRAVIS_TAG" != "x" ]; then
        export TRAVIS_TAG=${TRAVIS_TAG} ;
     else
        export TRAVIS_TAG=${TRAVIS_BRANCH}-latest ;
        git tag -f $TRAVIS_TAG ;
     fi
deploy:
  provider: releases
  on:
    branch: "release_test"
  api_key: "${AUTOMATION_TOKEN}"
  file_glob: true
  file: dist/*.whl
  skip_cleanup: true

